// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatRoom struct {
	UserID uuid.UUID `json:"user_id"`
	RoomID uuid.UUID `json:"room_id"`
}

type Message struct {
	MessageID  uuid.UUID          `json:"message_id"`
	UserID     uuid.UUID          `json:"user_id"`
	RoomID     uuid.UUID          `json:"room_id"`
	Text       pgtype.Text        `json:"text"`
	Multimedia []byte             `json:"multimedia"`
	IsRead     pgtype.Bool        `json:"is_read"`
	ReadAt     pgtype.Timestamptz `json:"read_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	RoleID      uuid.UUID   `json:"role_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Room struct {
	RoomID      uuid.UUID   `json:"room_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	RoomType    string      `json:"room_type"`
}

type Session struct {
	SessionID uuid.UUID          `json:"session_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Expires   pgtype.Timestamptz `json:"expires"`
}

type User struct {
	UserID    uuid.UUID          `json:"user_id"`
	LastName  string             `json:"last_name"`
	FirstName string             `json:"first_name"`
	Gender    string             `json:"gender"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	RoleID    uuid.UUID          `json:"role_id"`
}
